### ISSUE TITLE
As a user, I can see the price of each ingredient, so I know how much each individual item costs.

### ISSUE THREAD

**Issue by jlbrewe** [Clemson-Software-Engineering/Recipe-Builder#19]
- [x] Search items/ingredients in API - @dcathapermal (2 hours)
- [x] Design Final Page HTML - @Eaw7  (4 hours)
- [x] Add CSS to Final Page - @jlbrewe (2 hours)

Total Time: 8 hours

**Comment by dcathapermal** [comment]
Same issue with Walmart API (as the other sprint), but we developed views that can do all the methods we need, just with another API.
