### ISSUE TITLE
As a user, I can see what Walmart location the app is referring to, so I know where I will do my shopping.

### ISSUE THREAD

**Issue by jlbrewe** [Clemson-Software-Engineering/Recipe-Builder#22]
- [x] Connect to Walmart API - @dcathapermal (2 hour)
- [x] Search nearest store location - @dcathapermal (2 hour)
- [x] User location/form - @Eaw7  (2 hour)
- [x] Add CSS to Form Page @jlbrewe (1 hour)

Total Time: 6 hours

**Comment by dcathapermal** [comment]
Had an issue with the Walmart API being available, so we're looking into other ones.
